/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsRealAdapterRouteImport } from './routes/tests/real-adapter'

const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRealAdapterRoute = TestsRealAdapterRouteImport.update({
  id: '/tests/real-adapter',
  path: '/tests/real-adapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto': typeof AutoRoute
  '/tests/real-adapter': typeof TestsRealAdapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto': typeof AutoRoute
  '/tests/real-adapter': typeof TestsRealAdapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto': typeof AutoRoute
  '/tests/real-adapter': typeof TestsRealAdapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auto' | '/tests/real-adapter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auto' | '/tests/real-adapter'
  id: '__root__' | '/' | '/auto' | '/tests/real-adapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoRoute: typeof AutoRoute
  TestsRealAdapterRoute: typeof TestsRealAdapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/real-adapter': {
      id: '/tests/real-adapter'
      path: '/tests/real-adapter'
      fullPath: '/tests/real-adapter'
      preLoaderRoute: typeof TestsRealAdapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoRoute: AutoRoute,
  TestsRealAdapterRoute: TestsRealAdapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
