export type ComfyNode = {
	inputs: Record<string, [string, number] | string | number>;
	class_type: string;
	_meta?: {
		title: string;
	};
};

type ComfyPrompt = Record<string, ComfyNode>;

export type SubmitPromptBody = {
	prompt: ComfyPrompt;
	prompt_id?: string;
	extra_data?: Record<string, unknown>;
	partial_execution_targets?: string[];
};

type PromptAccepted = {
	prompt_id: string;
	number: number;
};

export type ProxyWsInbound =
	| { type: "submit_prompt"; data: SubmitPromptBody }
	| { type: "ping"; data?: unknown };

export type ProxyWsOutbound =
	| { type: "prompt_accepted"; data: PromptAccepted }
	| { type: "error"; data: ProxyError }
	| { type: string; data: unknown };

export type ProxyError = {
	message: string;
	code?: ErrorCode;
	userId?: string;
	promptId?: string;
	timestamp?: number;
	retryable?: boolean;
	context?: Record<string, unknown>;
};

export const ErrorCode = {
	INVALID: "INVALID",
	MAX_CONNECTIONS_EXCEEDED: "MAX_CONNECTIONS_EXCEEDED",
	QUEUE_FULL: "QUEUE_FULL",
	SESSION_NOT_READY: "SESSION_NOT_READY",
	TIMEOUT: "TIMEOUT",
	UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export type ComfyWsMessage = { type: string; data: unknown };

type ConnectionState = "connecting" | "connected" | "disconnected";

// Extended WebSocket type for Bun's ServerWebSocket that includes custom properties
import type { ServerWebSocket } from "bun";

export interface ExtendedServerWebSocket<T> extends ServerWebSocket<T> {
	userId?: string;
	sessionId?: string;
}

export type Session = {
	sessionId: string; // Composite key: userId:clientId
	userId: string;
	clientId: string; // generated by proxy for Comfy
	sid?: string; // Comfy-assigned session id (from status)
	currentPromptId?: string;
	comfyWs?: WebSocket;
	clientWs?: ExtendedServerWebSocket<unknown>;
	lastActiveAt: number;
	connectionState: ConnectionState;
	readyPromise?: Promise<void>; // Resolves when session is ready with sid
	markReady?: () => void; // Callback to resolve readyPromise
	reconnectAttempts?: number;
	isReconnecting?: boolean;
	reconnectTimeoutId?: Timer;
	correlationId?: string; // Correlation ID for request tracing
};

export type MetricsResponse = {
	active_sessions: number;
	active_connections: number;
	uptime_seconds: number;
	memory_usage: NodeJS.MemoryUsage;
	circuit_breaker_state: string;
	queued_prompts: Record<string, number>;
	detailed_sessions?: Array<{
		userId: string;
		clientId: string;
		connectionState: ConnectionState;
		lastActiveAt: number;
	}>;
	// Performance metrics
	performance?: {
		averageConnectionTimeMs: number;
		averagePromptSubmissionTimeMs: number;
		totalPromptsProcessed: number;
		totalErrors: number;
		errorRate: number; // errors / total requests
	};
};

export type QueuedPrompt = {
	prompt: ComfyPrompt;
	prompt_id?: string;
	extra_data?: Record<string, unknown>;
	partial_execution_targets?: string[];
	timestamp: number;
	userId: string;
	retryCount?: number; // Number of times this prompt has been retried
};
