export type ComfyNode = {
	inputs: Record<string, [string, number] | string | number>;
	class_type: string;
	_meta?: {
		title: string;
	};
};

export type ComfyPrompt = Record<string, ComfyNode>;

export type SubmitPromptBody = {
	prompt: ComfyPrompt;
	prompt_id?: string;
	extra_data?: Record<string, unknown>;
	partial_execution_targets?: string[];
	webhook_url?: string;
	webhook_secret?: string;
};

export type PromptAccepted = {
	prompt_id: string;
	number: number;
};

export type ProxyWsInbound =
	| { type: "submit_prompt"; data: SubmitPromptBody }
	| { type: "ping"; data?: unknown };

export type ProxyWsOutbound =
	| { type: "prompt_accepted"; data: PromptAccepted }
	| { type: "error"; data: { message: string; code?: string } }
	| { type: string; data: unknown };

export type ComfyWsMessage = { type: string; data: unknown };

export type ConnectionState = "connecting" | "connected" | "disconnected";

export type Session = {
	userId: string;
	clientId: string; // generated by proxy for Comfy
	sid?: string; // Comfy-assigned session id (from status)
	currentPromptId?: string;
	comfyWs?: WebSocket;
	clientWs?: WebSocket;
	lastActiveAt: number;
	connectionState: ConnectionState;
	webhooks?: Record<string, { url: string; secret?: string }>; // prompt_id -> webhook config
};

export type MetricsResponse = {
	active_sessions: number;
	active_connections: number;
	uptime_seconds: number;
	memory_usage: NodeJS.MemoryUsage;
	circuit_breaker_state: string;
	queued_prompts: Record<string, number>;
	detailed_sessions?: Array<{
		userId: string;
		clientId: string;
		connectionState: ConnectionState;
		lastActiveAt: number;
	}>;
};

export type QueuedPrompt = {
	prompt: ComfyPrompt;
	prompt_id?: string;
	extra_data?: Record<string, unknown>;
	partial_execution_targets?: string[];
	timestamp: number;
	userId: string;
};
